[package]
name = "save-saver"
version = "0.1.0"
edition = "2021"

[dependencies]
tui = "0.19"
crossterm = "0.25"
dirs = "4.0.0"
rfd = "0.10.0"
fs_extra = "1.2.0"
chrono = "0.4.23"
zip = "0.6.3"
walkdir = "2.3.2"